mod rainbow;
mod pulse;
mod chase;
mod audio_spectrum;
mod audio_pulse;
mod audio_chase;
mod audio_ripple;
mod audio_waterfall;
mod audio_sparkle;
mod audio_energy;
mod audio_pastel;

pub use rainbow::rainbow_cycle;
pub use pulse::pulse;
pub use chase::color_chase;
pub use audio_spectrum::audio_spectrum;
pub use audio_pulse::audio_pulse;
pub use audio_chase::audio_chase;
pub use audio_ripple::audio_ripple;
pub use audio_waterfall::audio_waterfall;
pub use audio_sparkle::audio_sparkle;
pub use audio_energy::audio_energy;
pub use audio_pastel::audio_pastel;
