mod rainbow;
mod pulse;
mod chase;
mod audio_chase;
mod audio_sparkle;
mod audio_energy;
mod audio_hybrid;
mod audio_synesthesia4;
mod audio_harmonic2;
mod audio_harmonic3;
mod audio_harmonic4;
mod audio_harmonic5;
mod audio_harmonic6;
mod audio_harmonic7;
mod audio_harmonic8;
mod audio_fire;
mod pacman;
mod retro_arcade;
mod game_of_life;

pub use rainbow::rainbow_cycle;
pub use pulse::pulse;
pub use chase::color_chase;
pub use audio_chase::audio_chase;
pub use audio_sparkle::audio_sparkle;
pub use audio_energy::audio_energy;
pub use audio_hybrid::audio_hybrid;
pub use audio_synesthesia4::audio_synesthesia4;
pub use audio_harmonic2::audio_harmonic2;
pub use audio_harmonic3::audio_harmonic3;
pub use audio_harmonic4::audio_harmonic4;
pub use audio_harmonic5::audio_harmonic5;
pub use audio_harmonic6::audio_harmonic6;
pub use audio_harmonic7::audio_harmonic7;
pub use audio_harmonic8::audio_harmonic8;
pub use audio_fire::audio_fire;
pub use pacman::pacman;
pub use retro_arcade::retro_arcade;
pub use game_of_life::game_of_life;
