mod rainbow;
mod pulse;
mod chase;
mod audio_spectrum;
mod audio_pulse;
mod audio_chase;
mod audio_ripple;
mod audio_waterfall;
mod audio_sparkle;
mod audio_energy;
mod audio_pastel;
mod audio_hybrid;
mod audio_synesthesia;
mod audio_synesthesia2;
mod audio_synesthesia3;
mod audio_synesthesia4;
mod audio_harmonic;
mod audio_harmonic2;
mod audio_harmonic3;
mod audio_harmonic4;
mod audio_harmonic5;

pub use rainbow::rainbow_cycle;
pub use pulse::pulse;
pub use chase::color_chase;
pub use audio_spectrum::audio_spectrum;
pub use audio_pulse::audio_pulse;
pub use audio_chase::audio_chase;
pub use audio_ripple::audio_ripple;
pub use audio_waterfall::audio_waterfall;
pub use audio_sparkle::audio_sparkle;
pub use audio_energy::audio_energy;
pub use audio_pastel::audio_pastel;
pub use audio_hybrid::audio_hybrid;
pub use audio_synesthesia::audio_synesthesia;
pub use audio_synesthesia2::audio_synesthesia2;
pub use audio_synesthesia3::audio_synesthesia3;
pub use audio_synesthesia4::audio_synesthesia4;
pub use audio_harmonic::audio_harmonic;
pub use audio_harmonic2::audio_harmonic2;
pub use audio_harmonic3::audio_harmonic3;
pub use audio_harmonic4::audio_harmonic4;
pub use audio_harmonic5::audio_harmonic5;
